#!/bin/bash
# scripts/register-kernel.sh
#
# Sourced by dev-setup.sh once the target env is active and the local package
# is installed. Registers (or repairs) the Jupyter kernelspec named
# $KERNEL_NAME, then rewrites its kernel.json to launch through a small
# activation wrapper (start-kernel.sh) instead of the env's bare python path.
#
# Why the wrapper: a Jupyter server hosted outside the env (e.g. Anvil's HPC
# Jupyter install) launches the kernel with none of the env's PATH or
# activate.d hook vars (PROJ_DATA, GDAL_DATA, ...), so subprocesses (!cmd,
# shell magics) and activate.d-dependent packages break even though
# in-notebook Python imports still work.
#
# Expects (set by the caller): KERNEL_NAME, CLEAN_MODE, PACKAGE_MANAGER,
# MICROMAMBA_CMD (when PACKAGE_MANAGER=micromamba). ENV_PREFIX is read if
# already set (dev-setup.sh exports it after activation); otherwise it is
# derived from the active python.
#
# Standalone-safe: also runnable directly as `bash scripts/register-kernel.sh`
# in an already-activated env (see docs/installation.md) — any of the above
# left unset are derived below instead of failing.
_REGISTER_KERNEL_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_REGISTER_KERNEL_REPO_ROOT="$(cd "$_REGISTER_KERNEL_SCRIPT_DIR/.." && pwd)"
if [[ -z "${KERNEL_NAME:-}" ]]; then
  KERNEL_NAME="$(awk -F': *' '$1=="name"{print $2; exit}' "$_REGISTER_KERNEL_REPO_ROOT/environment.yml" 2>/dev/null)"
fi
if [[ -z "${KERNEL_NAME:-}" ]]; then
  echo "Error: KERNEL_NAME not set and could not be derived from ${_REGISTER_KERNEL_REPO_ROOT}/environment.yml." >&2
  exit 1
fi
CLEAN_MODE="${CLEAN_MODE:-false}"
if [[ -z "${PACKAGE_MANAGER:-}" ]]; then
  if command -v micromamba >/dev/null 2>&1; then
    PACKAGE_MANAGER="micromamba"
  else
    PACKAGE_MANAGER="conda"
  fi
fi
MICROMAMBA_CMD="${MICROMAMBA_CMD:-micromamba}"

# Refuse to register a kernel for an env that isn't actually the active one —
# otherwise this silently registers a kernel pointing at the wrong prefix.
_register_kernel_active_prefix="$(python -c 'import sys; print(sys.prefix)' 2>/dev/null || true)"
if [[ "$(basename "${_register_kernel_active_prefix:-}")" != "$KERNEL_NAME" ]]; then
  echo "Error: environment '$KERNEL_NAME' is not active (active python prefix: ${_register_kernel_active_prefix:-<none>})." >&2
  echo "  Activate it first, e.g.: micromamba activate $KERNEL_NAME  (or: conda activate $KERNEL_NAME)" >&2
  exit 1
fi

# Check if kernel exists
if python - "$KERNEL_NAME" <<'PY'
from jupyter_client.kernelspec import KernelSpecManager
import sys
name = sys.argv[1]
specs = KernelSpecManager().find_kernel_specs()
sys.exit(0 if name in specs else 1)
PY
then
  KERNEL_EXISTS="true"
else
  KERNEL_EXISTS="false"
fi

# Remove kernel if --clean is specified and it exists
if [[ "$CLEAN_MODE" == "true" && "$KERNEL_EXISTS" == "true" ]]; then
  echo "Removing existing Jupyter kernel: $KERNEL_NAME"
  python -m ipykernel uninstall -y --name "$KERNEL_NAME" 2>/dev/null || true
  KERNEL_EXISTS="false"
fi

# Always (re)install so re-running the script also repairs kernels registered
# by older versions of this script (no activation wrapper). ipykernel install
# already overwrites an existing kernelspec, so this stays idempotent.
echo "Installing Jupyter kernel: $KERNEL_NAME"
# Use --user flag to make kernel visible globally (not just within the environment)
python -m ipykernel install --user --name "$KERNEL_NAME" --display-name "$KERNEL_NAME"
echo "✓ Jupyter kernel installation completed successfully!"

KERNEL_DIR="$(python - "$KERNEL_NAME" <<'PY'
from jupyter_client.kernelspec import KernelSpecManager
import sys
print(KernelSpecManager().get_kernel_spec(sys.argv[1]).resource_dir)
PY
)"
ENV_PREFIX="${ENV_PREFIX:-$(python -c 'import sys; print(sys.prefix)')}"

WRAPPER_PATH="$KERNEL_DIR/start-kernel.sh"
echo "Writing kernel activation wrapper: $WRAPPER_PATH"

# Build the wrapper as a single-quoted template (no shell expansion at all,
# so "$@" and "$(...)" survive verbatim) and fill in registration-time values
# via token substitution, matching whichever package manager created this
# env so activation works whether the env came from micromamba or conda.
if [[ "$PACKAGE_MANAGER" == "micromamba" ]]; then
  MICROMAMBA_ABS="$(command -v "$MICROMAMBA_CMD" 2>/dev/null || echo "$MICROMAMBA_CMD")"
  WRAPPER_CONTENT='#!/usr/bin/env bash
# Auto-generated by dev-setup.sh. Activates the micromamba env before
# starting the kernel so subprocesses inherit PATH and activate.d vars.
set -eo pipefail
eval "$(__MICROMAMBA_BIN__ shell hook --shell bash)"
micromamba activate "__ENV_PREFIX__"
# Keep the kernel off user-site (~/.local) so it cannot shadow the env packages.
export PYTHONNOUSERSITE=1
exec python -m ipykernel_launcher "$@"
'
  WRAPPER_CONTENT="${WRAPPER_CONTENT//__MICROMAMBA_BIN__/$MICROMAMBA_ABS}"
  WRAPPER_CONTENT="${WRAPPER_CONTENT//__ENV_PREFIX__/$ENV_PREFIX}"
else
  CONDA_BASE="$(conda info --base 2>/dev/null || true)"
  if [[ -z "$CONDA_BASE" && -n "${CONDA_EXE:-}" ]]; then
    CONDA_BASE="$(dirname "$(dirname "$CONDA_EXE")")"
  fi
  if [[ -z "$CONDA_BASE" ]]; then
    echo "Error: could not determine the conda base install (conda info --base failed and CONDA_EXE is unset)." >&2
    echo "  Re-run dev-setup.sh from a shell where conda is initialized (e.g. after 'module load conda')." >&2
    exit 1
  fi
  WRAPPER_CONTENT='#!/usr/bin/env bash
# Auto-generated by dev-setup.sh. Activates the conda env before starting
# the kernel so subprocesses inherit PATH and activate.d vars.
set -eo pipefail
source "__CONDA_BASE__/etc/profile.d/conda.sh"
conda activate "__ENV_PREFIX__"
# Keep the kernel off user-site (~/.local) so it cannot shadow the env packages.
export PYTHONNOUSERSITE=1
exec python -m ipykernel_launcher "$@"
'
  WRAPPER_CONTENT="${WRAPPER_CONTENT//__CONDA_BASE__/$CONDA_BASE}"
  WRAPPER_CONTENT="${WRAPPER_CONTENT//__ENV_PREFIX__/$ENV_PREFIX}"
fi

printf '%s' "$WRAPPER_CONTENT" > "$WRAPPER_PATH"
chmod +x "$WRAPPER_PATH"

# Point kernel.json at the wrapper, preserving display_name/language/metadata.
# {connection_file} must stay a literal Jupyter template placeholder.
python - "$KERNEL_DIR" "$WRAPPER_PATH" <<'PY'
import json
import sys

kernel_dir, wrapper_path = sys.argv[1], sys.argv[2]
kernel_json_path = f"{kernel_dir}/kernel.json"
with open(kernel_json_path) as f:
    spec = json.load(f)
spec["argv"] = [wrapper_path, "-f", "{connection_file}"]
with open(kernel_json_path, "w") as f:
    json.dump(spec, f, indent=1)
PY
echo "✓ Kernel registered to launch via activation wrapper ($WRAPPER_PATH)"
